# -*- coding: utf-8 -*-
"""bai tap tuan 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4nOXndkZkO1HiubB_NKri6_mEpgs4J_
"""

def slh(a,b):
  if a > b:
    return a
  else:
    return b
a,b=map(int,input("").split())

def doi_so(a,b):
  a,b=b,a
  return a, b
print(doi_so(2,3))

def snt(n):
  for i in range(2,int(n**0.5)+1):
    if n%i==0:
      return False
    else:
      return True
print(snt(13))

def shh(n):
  tong=0
  for i in range(1,n):
    if n%i==0:
      tong+=i
  if tong == n:
    return True
  else:
    return False
print(shh(6))

def gt(n):
  if n ==0:
    return 0
  if n==1:
    return 1
  else:
    return n*gt(n-1)
print(gt(4))

def may_tinh_bo_tui(num1, num2, operator):
    if operator == '+':
        result = num1 + num2
    elif operator == '-':
        result = num1 - num2
    elif operator == '*':
        result = num1 * num2
    elif operator == '/':
        result = num1 / num2
    elif operator == '%':
        result = num1 % num2
    elif operator == '//':
        result = num1 // num2
    else:
        return "Toán tử không hợp lệ"

    return round(result, 2)
print(may_tinh_bo_tui(2, 3, '+'))      # 5.0
print(may_tinh_bo_tui(12, 4, '/'))     # 3.0
print(may_tinh_bo_tui(23.98, 23.12, '*'))  # 552.34
print(may_tinh_bo_tui(70, 3, '%'))     # 1.0
print(may_tinh_bo_tui(70, 3, '//'))    # 23.0
print(may_tinh_bo_tui(12, 30.094, '-'))# -18.09

def hamming_distance(x, y):
    # XOR để tìm các bit khác nhau
    diff = x ^ y
    # Đếm số bit 1 trong kết quả XOR
    return bin(diff).count('1')

# Test
print(hamming_distance(1, 4))          # 2
print(hamming_distance(123456, 32321))

def tong(n):
  tong=0
  while n >0:
    tong+=n%10
    n//=10
  return tong
print(tong(1234))

def isomorphic(a, b):
    if len(a) != len(b):
        return False

    map_a_to_b = {}
    map_b_to_a = {}

    for char_a, char_b in zip(a, b):
        # Kiểm tra ánh xạ a -> b
        if char_a in map_a_to_b:
            if map_a_to_b[char_a] != char_b:
                return False
        else:
            map_a_to_b[char_a] = char_b


        if char_b in map_b_to_a:
            if map_b_to_a[char_b] != char_a:
                return False
        else:
            map_b_to_a[char_b] = char_a

    return True



print(isomorphic("egg", "add"))
print(isomorphic("paper", "title"))    # true
print(isomorphic("foo", "bar"))        # false
print(isomorphic("show", "same"))      # true
print(isomorphic("show", "seem"))      # false