# -*- coding: utf-8 -*-
"""baitaptuan6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18nK86c-4KbKjIYi0Y-tehmG7D1YqZmuH
"""

def w1(a):
  b=[]
  for i in a:
    if i not in b:
      b.append(i)
  return b
a=list(map(int,input().split()))
print(w1(a))

def w2(a):
  tong=0
  b=[]
  for i in a:
    tong+=i
    b.append(tong)
  return b
a=list(map(int,input().split()))
print(w2(a))

def w3(a,b):
    c=len(a)
    k=b%c
    d=(a[k:]+a[:k])
    return d
a=list(map(int,input().split()))
b=int(input())
print(w3(a,b))

def w4(a):
    b={}
    c=a.split()
    for d in c:
        key,val=d.split(':')
        if key not in b:
            b[key]=[]
        b[key].append(val)
    return b
a=input()
print(w4(a))

def w5(a):
    b={}
    p=0
    n=0
    z=0
    for i in a:
        if i>0:
            p+=1
        elif i<0:
            n+=1
        else:
            z+=1
    b['positive']=p
    b['negative']=n
    b['zero']=z
    return b
a=list(map(int,input().split()))
print(w5(a))

def w6(a):
    return sum(a)
a=list(map(int,input().split()))
print(w6(a))

def w7(a):
    b=a[0]
    c=a[len(a)-1]
    d=a[::-1]
    return (b,c,d)
a=tuple(map(int,input().split()))
print(w7(a))

chuoi_nhap = input()
list_chuoi = chuoi_nhap.split()
dem_dict = {}
for chuoi in list_chuoi:
    if chuoi in dem_dict:
        dem_dict[chuoi] += 1
    else:
        dem_dict[chuoi] = 1
print(dem_dict)

dict1 = eval(input())
dict2 = eval(input())
dict_merged = {}
for key in dict1:
    dict_merged[key] = dict1[key]
for key in dict2:
    if key in dict_merged:
        dict_merged[key] += dict2[key]
    else:
        dict_merged[key] = dict2[key]
dict_sorted = dict(sorted(dict_merged.items()))
print("Dictionary sau khi gộp và sắp xếp:")
print(dict_sorted)

ds = list(map(int, input().split()))
k = int(input())
ket_qua = []
n = len(ds)

for i in range(n):
    for j in range(i + 1, n):
        if ds[i] + ds[j] == k:
            ket_qua.append((ds[i], ds[j]))
ket_qua.sort(key=lambda x: x[0])
print("Các cặp số có tổng bằng", k, "là:")
print(ket_qua)

t = tuple(map(int, input().split()))
chan = tuple(x for x in t if x % 2 == 0)
le   = tuple(x for x in t if x % 2 != 0)
print(chan)
print(le)

from collections import Counter
lst = list(map(int, input().split()))
dem = Counter(lst)
max_count = max(dem.values())
candidates = [num for num, count in dem.items() if count == max_count]
ket_qua = min(candidates)
print(ket_qua)

d = eval(input("Nhập dictionary (ví dụ {'a': 1, 'b': 2, 'c': 3}): "))
d_reverse = {v: k for k, v in d.items()}
print("Dictionary sau khi đảo ngược key và value:")
print(d_reverse)

list1 = list(map(int, input().split()))
list2 = list(map(int, input().split()))
giao = list(set(list1) & set(list2))
print(giao)

d = eval(input())
k = int(input())
new_dict = {key: value for key, value in d.items() if value > k}
print(new_dict)

n, m = map(int, input().split())
matrix = []
for i in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)
for row in matrix:
    print("".join(f"{x:4d}" for x in row))

n = int(input())
matrix = []
for i in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)
print([matrix[i][i] for i in range(n)])
print( [matrix[i][n - 1 - i] for i in range(n)])

n, m, k = map(int, input("Nhập n m k: ").split())
matrix = []

for i in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)
sum_row = sum(matrix[k])

sum_col = sum(matrix[i][k] for i in range(n))

print("Tổng hàng", k, "=", sum_row)
print("Tổng cột", k, "=", sum_col)

def vi_tri_max(lst):

    max_val = max(lst)

    return lst.index(max_val)

print(vi_tri_max([3, 7, 2, 9, 5]))

def tim_vi_tri(lst, k):
    for i, val in enumerate(lst):
        if val == k:
            return i
    return -1


print(tim_vi_tri([3, 7, 2, 9, 5], 9))
print(tim_vi_tri([3, 7, 2, 9, 5], 10))

s = input("Nhập các chuỗi cách nhau bởi dấu cách: ").split()

d = {}
for i, word in enumerate(s):
    if word not in d:
        d[word] = []
    d[word].append(i)
for key in d:
    d[key] = tuple(d[key])

print(d)

def vi_tri_chuoi():
    words = input("Nhập các chuỗi cách nhau bởi dấu cách: ").split()
    d = {}
    for i, word in enumerate(words):
        d.setdefault(word, []).append(i)
    for key in d:
        d[key] = tuple(d[key])
    print(d)